// The floors. Each map is a cross-section of the museum, one character per 16px tile (see parseLevel in sim.js).
// `par` is the fewest runs it can be done in; `solution` is a way to do it (checked by check.mjs, played by ?autoplay
// and by the preview), one script per run (see bot.js).
export const LEVELS = [
  {
    name: 'Closing Time',
    lesson: 'Climb up, take the jewel, and walk it out of the loading dock on the right.',
    par: 1,
    map: [
      '##############################',
      '#............................#',
      '#............................#',
      '#.........$..................#',
      '#####H###############H########',
      '#....H...............H.......X',
      '#....H...............H.......X',
      '#@...H...............H.......X',
      '##############################',
    ],
    solution: [
      [['go', 5], ['up'], ['go', 10], ['act'], ['go', 21], ['down'], ['go', 29]],
    ],
  },
  {
    name: 'Hold the Door',
    lesson: 'A plate holds its door open only while one of you stands on it. Stand on the plate and press Stop: that copy waits there in every run after.',
    par: 2,
    map: [
      '##############################',
      '#...................A........#',
      '#...................A........#',
      '#...................A....$...#',
      '####H######################H##',
      '#...H......................H.X',
      '#...H......................H.X',
      '#@..H......a...............H.X',
      '##############################',
    ],
    solution: [
      [['go', 11], ['stop']],
      [['go', 4], ['up'], ['go', 25], ['act'], ['go', 27], ['down'], ['go', 29]],
    ],
  },
  {
    name: 'Night Watch',
    lesson: 'A guard chases the first of you he sees, any of you, and takes away whoever he catches. One of you can lead him off.',
    par: 2,
    map: [
      '##############################',
      '#............................#',
      '#............................#',
      '#............................#',
      '##H######################H####',
      '#.H......................H...X',
      '#.H......................H...X',
      '#@H................$G....H...X',
      '##############################',
    ],
    guards: [{ face: -1 }],
    solution: [
      [['wait', 2], ['go', 13], ['go', 1]],
      [['go', 2], ['up'], ['go', 25], ['down'], ['go', 19], ['act'], ['go', 29]],
    ],
  },
  {
    name: 'Eyes Up',
    lesson: 'A camera looks one way, then the other, the same way every run, and sounds the alarm if it sees any of you. Right underneath it, it can’t see you at all.',
    par: 1,
    map: [
      '##############################',
      '#.........V.........V........#',
      '#............................#',
      '#.......................$....#',
      '##H#######################H###',
      '#.H.......................H..X',
      '#.H.......................H..X',
      '#@H.......................H..X',
      '##############################',
    ],
    cams: [{ from: 22, to: 158, hold: 2.2, swing: 0.5, len: 7, fov: 14 }, { from: 158, to: 22, hold: 2.2, swing: 0.5, len: 7, fov: 14 }],
    solution: [
      [['go', 2], ['up'], ['wait', 5.5], ['go', 10], ['go', 20], ['go', 24], ['act'], ['go', 26], ['down'], ['go', 29]],
    ],
  },
  {
    name: 'Tripwire',
    lesson: 'A laser sounds the alarm when any of you crosses it, and an alarm ends the run. Some blink. Some go dark while a plate is held.',
    par: 2,
    map: [
      '##############################',
      '#...........!.......!........#',
      '#...........!.......!........#',
      '#...........!.......!...$....#',
      '########H#################H###',
      '#.......H.......#.........H..X',
      '#.......H.......#.........H..X',
      '#@...c..H.......#.........H..X',
      '##############################',
    ],
    lasers: [{ off: 'c' }, { cycle: [1.5, 1.5] }],
    solution: [
      [['go', 5], ['stop']],
      [['go', 8], ['up'], ['go', 18], ['wait', 7.6], ['go', 24], ['act'], ['go', 26], ['down'], ['go', 29]],
    ],
  },
  {
    name: 'The Key',
    lesson: 'Walk into a locked door with the key and it opens for good. There is only one key, and you carry one thing at a time: grab the jewel and you put the key down.',
    par: 1,
    map: [
      '##############################',
      '#............................#',
      '#............................#',
      '#..k.........................#',
      '##########H###################',
      '#.........H.........%........X',
      '#.........H.........%........X',
      '#@........H.........%...$....X',
      '##############################',
    ],
    solution: [
      [['go', 10], ['up'], ['go', 3], ['act'], ['go', 10], ['down'], ['go', 24], ['act'], ['go', 29]],
    ],
  },
  {
    name: 'Two of You',
    lesson: 'This door needs both its plates held at once, and someone still has to walk through it.',
    par: 3,
    map: [
      '##############################',
      '#....................B.......#',
      '#....................B.......#',
      '#.....b..............B...$...#',
      '###H#######################H##',
      '#..H.......................H.X',
      '#..H.......................H.X',
      '#@.H..........b............H.X',
      '##############################',
    ],
    solution: [
      [['go', 14], ['stop']],
      [['go', 3], ['up'], ['go', 6], ['stop']],
      [['go', 3], ['up'], ['go', 25], ['act'], ['go', 27], ['down'], ['go', 29]],
    ],
  },
  {
    name: 'Pass It On',
    lesson: 'Whoever holds the key keeps it, even after their run stops. To share it, one of you has to put it down where a later one can find it.',
    par: 2,
    map: [
      '##############################',
      '#...........%................#',
      '#...........%................#',
      '#@.k........%.......b......H.#',
      '###########################H##',
      'X................%....B....H.#',
      'X................%....B....H.#',
      'X.........$......%....B....H.#',
      '##############################',
    ],
    solution: [
      [['go', 3], ['act'], ['go', 13], ['act'], ['go', 20], ['stop']],
      [['go', 12], ['wait', 3.5], ['go', 13], ['act'], ['go', 27], ['down'], ['go', 10], ['act'], ['go', 0]],
    ],
  },
  {
    name: 'Decoy Duty',
    lesson: 'The guard walks right past the plate that opens the vault. Whoever stands on it won’t last long, unless another of you keeps him busy somewhere else.',
    par: 3,
    map: [
      '##############################',
      '#............................#',
      '#............................#',
      '#...Ga.......................#',
      '###############H########H#####',
      '#...........A..H........H...X',
      '#...........A..H........H...X',
      '#.$.........A..H........H.@.X',
      '##############################',
    ],
    guards: [{ beat: [2, 12], face: 1, pause: 1 }],
    solution: [
      [['go', 24], ['up'], ['go', 19], ['spotted'], ['go', 28]],
      [['go', 15], ['wait', 5], ['up'], ['go', 5], ['stop']],
      [['go', 13], ['go', 2], ['act'], ['go', 29]],
    ],
  },
  {
    name: 'Security Desk',
    lesson: 'The plate at the security desk cuts the lasers, but the desk camera isn’t on it. Stand there only while the camera looks the other way.',
    par: 2,
    map: [
      '##############################',
      '#........V...................#',
      '#............................#',
      '#..........d.................#',
      '#H############################',
      '#H..........!.....!.........X',
      '#H..........!.....!.........X',
      '#H@.........!.....!...$.....X',
      '##############################',
    ],
    cams: [{ from: 158, to: 22, hold: 3, swing: 0.5, len: 6, fov: 14 }],
    lasers: [{ off: 'd' }, { off: 'd' }],
    solution: [
      [['go', 1], ['up'], ['wait', 3], ['go', 8], ['wait', 6.5], ['go', 11], ['wait', 10], ['go', 8], ['stop']],
      [['go', 11], ['wait', 7.5], ['go', 22], ['act'], ['go', 29]],
    ],
  },
  {
    name: 'Changing of the Guard',
    lesson: 'Two guards, one on each floor. A ladder is a good place to hang on while a guard goes by underneath.',
    par: 3,
    map: [
      '##############################',
      'X............................#',
      'X............................#',
      'X.................G..........#',
      '#####H##################H#####',
      '#....H..................H....#',
      '#....H..................H....#',
      '#@...H.........G......$.H....#',
      '##############################',
    ],
    guards: [{ beat: [10, 20], face: 1, pause: 1 }, { beat: [13, 20], face: -1, pause: 1 }],
    solution: [
      [['go', 7], ['spotted'], ['go', 1]],
      [['go', 5], ['climb', 0.6], ['wait', 3], ['down'], ['go', 24], ['up'], ['spotted'], ['go', 28]],
      [['go', 5], ['climb', 0.6], ['wait', 3], ['down'], ['go', 22], ['act'], ['go', 24], ['climb', 0.6], ['wait', 13.5], ['up'], ['go', 0]],
    ],
  },
  {
    name: 'The Loading Dock',
    mustFail: [['key, decoy and thief, with the decoy far too early', [
      [['go', 3], ['up'], ['go', 6], ['up'], ['go', 17], ['go', 26], ['act'], ['wait', 11], ['go', 17], ['wait', 14], ['go', 6], ['down'], ['go', 13], ['stop']],
      [['go', 19], ['wait', 5], ['go', 21], ['go', 1]],
      [['go', 3], ['up'], ['go', 11], ['wait', 19], ['go', 20], ['act'], ['go', 26], ['down'], ['go', 29]]]]],
    also: [['key, decoy and thief', [
      [['go', 3], ['up'], ['go', 6], ['up'], ['go', 17], ['go', 26], ['act'], ['wait', 11], ['go', 17], ['wait', 14], ['go', 6], ['down'], ['go', 13], ['stop']],
      [['go', 19], ['wait', 19], ['go', 21], ['go', 1]],
      [['go', 3], ['up'], ['go', 11], ['wait', 19], ['go', 20], ['act'], ['go', 26], ['down'], ['go', 29]]]]],
    lesson: 'Everything at once. The key is up under a camera, the jewel is in the vault, and a guard stands in front of the dock door. Ten runs, and any one of you can walk it out.',
    par: 2,
    map: [
      '##############################',
      '#................V...........#',
      '#............................#',
      '#.........................k..#',
      '######H#######################',
      '#.....H.....%................#',
      '#.....H.....%................#',
      '#.....H.....%.......$........#',
      '###H######################H###',
      '#..H......................H..X',
      '#..H......................H..X',
      '#@.H......................H.GX',
      '##############################',
    ],
    cams: [{ from: 158, to: 22, hold: 2.5, swing: 0.5, len: 6, fov: 14 }],
    guards: [{ face: -1 }],
    solution: [
      [['go', 19], ['wait', 18], ['go', 21], ['go', 1]],
      [['go', 3], ['up'], ['go', 6], ['up'], ['go', 17], ['go', 26], ['act'], ['wait', 11], ['go', 17], ['wait', 14], ['go', 6], ['down'], ['go', 20], ['act'], ['go', 26], ['down'], ['go', 29]],
    ],
  },
];
