// The voyage home: five stretches of sea and the levels in each. See parse() in rules.js for how a map is read.
// crew: how many of each order the crew can give on this level (each is spent once used). legs: how many orders the
// scroll takes to reach each buoy, and then the harbour. needs: orders the level is meant to be impossible without
// (check.mjs makes sure).

export const CHAPTERS = [
  { name: 'The Far Isles', blurb: 'Where the voyage turned for home.' },
  { name: 'The Tidewater', blurb: 'Currents run hard between the islands here.' },
  { name: 'The Flotsam Sea', blurb: 'Wreckage and worse drift on these waters.' },
  { name: 'The Drowned Docks', blurb: 'The pilings of a sunken port still stand.' },
  { name: 'Home Waters', blurb: 'Every rock here has a name. Nearly home.' },
];

export const LEVELS = [
  /* ---------- The Far Isles: the basic orders ---------- */
  {
    name: 'Homeward Bound', chapter: 0,
    harbour: "Palm Cove",
    log: "The long voyage is over, and the far isles are behind us. Time to sail home.",
    moored: "The first harbour of the long way home. Only a couple of dozen more!",
    fresh: ["hoist", "steady"],
    teach: [
      { who: 'captain', text: "Orders go on the scroll, one for each step. Drag them there from the crew, or just tap them." },
      { who: 'bosun', text: "<b>Hoist</b> the sail and she sails a square every step while it’s up. <b>Steady</b> keeps her doing what she’s doing." },
      { who: 'captain', text: "Fill the scroll, then <b>Set sail!</b> Round the buoy first, then make for the harbour." },
    ],
    map: [
      '###H###',
      '##...##',
      '#.....#',
      '#..1..#',
      '#.....#',
      '#.....#',
      '##.s.##',
      '#######',
    ],
    facing: 'N', legs: [3, 3],
    crew: { hoist: 1, steady: 5 },
    needs: ['hoist'],
  },
  {
    name: 'Port and Starboard', chapter: 0,
    harbour: "Turtle Bay",
    log: "An island in the way. Time to learn to steer.",
    fresh: ["port", "starboard"],
    teach: [
      { who: 'captain', text: "<b>Port</b> turns her a quarter to her left, <b>Starboard</b> a quarter to her right. <i>Her</i> left and right: look which way her bow points! Her red lamp is on the port side, her green on starboard." },
    ],
    map: [
      '####H##',
      '#.....#',
      '#.###.#',
      '#1###.#',
      '#.###.#',
      '#.....#',
      '##s####',
    ],
    facing: 'N', legs: [4, 6],
    crew: { hoist: 1, steady: 5, port: 2, starboard: 2 },
    needs: ['port', 'starboard'],
  },
  {
    name: 'The Whale Road', chapter: 0,
    harbour: "Whalebone Quay",
    log: "Whales cross the sound here, back and forth, all day long.",
    fresh: ["strike"],
    teach: [
      { who: 'bosun', text: "A whale! <b>Strike</b> the sail and she stops. Let it pass, then <b>Hoist</b> again." },
      { who: 'captain', text: "The numbers on the water show where it’ll be after each step of the scroll." },
    ],
    map: [
      '###H###',
      '###.###',
      '.......',
      '###.###',
      '##.1.##',
      '##...##',
      '##.s.##',
      '#######',
    ],
    facing: 'N', legs: [2, 6],
    crew: { hoist: 2, strike: 1, steady: 6, port: 1, starboard: 1 },
    beasts: [{ kind: 'whale', at: [0, 2], route: 'EEEEEE', back: true, phase: 0 }],
    needs: ['strike'],
  },

  /* ---------- The Tidewater: the anchor ---------- */
  {
    name: 'Slack Water', chapter: 1,
    harbour: "Tideford",
    log: "The mainsail tore in the night and Bo’s still stitching it. We’ll ride the tide today.",
    fresh: ["anchor"],
    teach: [
      { who: 'anchor', text: "Marlo, at your service. See those streaks? A <b>current</b> carries her a square every step, sail up or down." },
      { who: 'anchor', text: "<b>Anchor</b> once to drop it, and nothing moves her. <b>Anchor</b> again to weigh it, and off she goes." },
    ],
    map: [
      '###H###',
      '###^###',
      '...^...',
      '###^###',
      '###^###',
      '###^###',
      '###^###',
      '#######',
    ],
    marks: { start: [3, 6], buoys: { 1: [3, 4] } },
    facing: 'N', legs: [2, 6],
    crew: { steady: 5, port: 1, starboard: 1, anchor: 2 },
    beasts: [{ kind: 'whale', at: [0, 2], route: 'EEEEEE', back: true, phase: 5 }],
    needs: ['anchor'],
  },
  {
    name: 'Shark Rock', chapter: 1,
    harbour: "Finrock",
    log: "A shark lives round the rock at the top of the tide race.",
    teach: [
      { who: 'anchor', text: "That shark goes round and round its rock. Hold at anchor till it’s gone by, then follow it round." },
    ],
    map: [
      '###H###',
      '##...##',
      '##.*.##',
      '##.1.##',
      '###^###',
      '###^###',
      '###^###',
      '#######',
    ],
    marks: { start: [3, 6] },
    facing: 'N', legs: [4, 6],
    crew: { hoist: 1, strike: 1, steady: 4, port: 2, starboard: 2, anchor: 2 },
    beasts: [{ kind: 'shark', at: [2, 1], route: 'EESSWWNN', phase: 3 }],
    needs: ['anchor'],
  },
  {
    name: 'The Wind Lane', chapter: 1,
    harbour: "Gusty Point",
    log: "Where the islands funnel the wind, it blows in lanes.",
    teach: [
      { who: 'bosun', text: "A <b>wind lane</b>! With the sail up, the wind blows her an extra square along it every step. Sail struck, it can’t touch her." },
      { who: 'anchor', text: "And at anchor nothing moves her, wind or no wind, sail or no sail." },
    ],
    map: [
      '#######',
      '###H###',
      '#..u..#',
      '###u###',
      '###u###',
      '###1###',
      '###u###',
      '###u###',
      '##...##',
      '##.s.##',
      '#######',
    ],
    facing: 'N', legs: [3, 4],
    crew: { hoist: 1, strike: 1, steady: 4, port: 1, starboard: 1, anchor: 2 },
    beasts: [{ kind: 'whale', at: [1, 2], route: 'EEEE', back: true, phase: 2 }],
    needs: ['anchor'],
  },
  {
    name: 'Crosscurrents', chapter: 1,
    harbour: "Twowhale Sound",
    log: "Two whales, two roads, and only the one Hoist in Bo’s arms today.",
    teach: [
      { who: 'captain', text: "Hurry past the first whale with the sail, and hold for the second with the anchor. Once she’s up, the sail stays up!" },
    ],
    map: [
      '##########',
      '#>rrrrrrH#',
      '#^####.###',
      '#^####.###',
      '#^####.###',
      '.^......##',
      '#^########',
      '#^########',
      '##########',
    ],
    marks: { start: [1, 7], buoys: { 1: [1, 2] } },
    facing: 'N', legs: [3, 5],
    crew: { hoist: 1, strike: 1, steady: 4, port: 1, starboard: 1, anchor: 2 },
    beasts: [
      { kind: 'whale', at: [0, 5], route: 'EEEEEEE', back: true, phase: 1 },
      { kind: 'whale', at: [6, 1], route: 'SSS', back: true, phase: 1 },
    ],
    needs: ['anchor', 'hoist'],
  },
  {
    name: 'The Maelstrom', chapter: 1,
    harbour: "Swirlwater",
    log: "Sailors tell of a whirlpool at the mouth of Swirlwater. The sailors are right.",
    teach: [
      { who: 'captain', text: "A <b>whirlpool</b>. Its swirl carries her round the eye, and the square above the eye drains straight down into it. Keep out of the eye!" },
    ],
    map: [
      '#######',
      '#######',
      '##...##',
      'H..@.##',
      '##...##',
      '####^##',
      '####^##',
      '#######',
    ],
    marks: { start: [4, 6] },
    facing: 'N', legs: [8],
    crew: { hoist: 1, strike: 1, steady: 4, port: 1, starboard: 1, anchor: 2 },
    beasts: [{ kind: 'shark', at: [2, 2], route: 'EESSWWNN', phase: 3 }],
    needs: ['anchor'],
  },

  /* ---------- The Flotsam Sea: the cannon ---------- */
  {
    name: 'Barrel Jam', chapter: 2,
    harbour: "Barrel Wharf",
    log: "Flotsam everywhere: a wreck’s cargo, lashed on rafts and drifting.",
    fresh: ["fire"],
    teach: [
      { who: 'gunner', text: "Pip, gunner! <b>Fire</b> sends a ball straight ahead, and it smashes the first barrels it meets, up to four squares off." },
      { who: 'gunner', text: "Mind the kick: every shot shoves her back a square. Don’t fire with the shore right behind you!" },
    ],
    map: [
      '###H###',
      '###.###',
      '###B###',
      '###.###',
      '###1###',
      '###.###',
      '###B###',
      '###.###',
      '###.###',
      '###s###',
      '#######',
    ],
    facing: 'N', legs: [6, 5],
    crew: { hoist: 1, steady: 8, fire: 2, port: 1, starboard: 1 },
    needs: ['fire'],
  },
  {
    name: 'Kickback', chapter: 2,
    harbour: "Backwater",
    log: "A dead end, and the buoy’s behind us.",
    teach: [
      { who: 'gunner', text: "No room to turn round, and the buoy’s right behind us. Now, what shoves a boat backwards...?" },
    ],
    map: [
      '#######',
      '#H..###',
      '###.###',
      '###2###',
      '###.###',
      '###B###',
      '###.###',
      '###s###',
      '###1###',
      '#######',
    ],
    facing: 'N', legs: [1, 5, 4],
    crew: { hoist: 1, strike: 1, steady: 7, fire: 2, port: 1, starboard: 1 },
    needs: ['fire'],
  },
  {
    name: 'Shark Scare', chapter: 2,
    harbour: "Sharktooth Inlet",
    log: "A shark patrols the only way in.",
    teach: [
      { who: 'gunner', text: "A ball won’t hurt a shark, but it gives it a fright: it turns tail and swims back the way it came." },
    ],
    map: [
      '#####',
      '##.##',
      '##.##',
      '#H.##',
      '##.##',
      '##.##',
      '##.##',
      '##.##',
      '##s##',
      '#####',
    ],
    facing: 'N', legs: [8],
    crew: { hoist: 1, strike: 1, steady: 5, fire: 2, port: 1, starboard: 1 },
    beasts: [{ kind: 'shark', at: [2, 6], route: 'NNNNN', back: true, phase: 3 }],
    needs: ['fire'],
  },
  {
    name: 'Powder Row', chapter: 2,
    harbour: "Powder Quay",
    log: "Barrels in a wind lane, and a whale for good measure.",
    teach: [
      { who: 'gunner', text: "With the wind at our backs, the kick only slows her down. Shoot on the move!" },
    ],
    map: [
      '#######',
      '###H###',
      '###u###',
      '###B###',
      '###u###',
      '...u...',
      '###u###',
      '###B###',
      '###u###',
      '###u###',
      '###.###',
      '###s###',
      '#######',
    ],
    facing: 'N', legs: [7],
    crew: { hoist: 1, strike: 1, steady: 5, fire: 3, port: 1, starboard: 1 },
    beasts: [{ kind: 'whale', at: [0, 5], route: 'EEEEEE', back: true, phase: 1 }],
    needs: ['fire'],
  },
  {
    name: 'Broadside', chapter: 2,
    harbour: "Broadside Bay",
    log: "A current full of wreckage, and a shark at the bottom of it.",
    teach: [
      { who: 'captain', text: "Two shots for a barrel and a shark. Spend them well." },
    ],
    map: [
      '#########',
      '#v#######',
      '#v#######',
      '#v#######',
      '#B#######',
      '#v#######',
      '#>>.....#',
      '#######.#',
      '#######H#',
      '#########',
    ],
    marks: { start: [1, 1], buoys: { 1: [1, 6] } },
    facing: 'S', legs: [5, 7],
    crew: { hoist: 1, strike: 1, steady: 6, fire: 2, port: 1, starboard: 1, anchor: 2 },
    beasts: [{ kind: 'shark', at: [3, 6], route: 'EEEE', back: true, phase: 7 }],
    needs: ['fire'],
  },

  /* ---------- The Drowned Docks: the grappling hook ---------- */
  {
    name: 'Old Pilings', chapter: 3,
    harbour: "Old Pilings",
    log: "The pilings of a drowned port stand in the rip.",
    fresh: ["grapple"],
    teach: [
      { who: 'hook', text: "Nell, with a hook! <b>Grapple</b> throws it at a post up to four squares straight ahead, and we haul her right up to it." },
      { who: 'hook', text: "Nothing else moves her that step, current or wind. And posts are solid: turn away from it after!" },
    ],
    map: [
      '########',
      '#s.vv.P#',
      '#..vv1.#',
      '###**..#',
      '#.vv...#',
      'P.vv..##',
      '#.**####',
      '#H######',
      '########',
    ],
    facing: 'E', legs: [3, 7],
    crew: { hoist: 1, strike: 1, steady: 5, port: 2, starboard: 2, grapple: 2 },
    needs: ['grapple'],
  },
  {
    name: 'Against the Wind', chapter: 3,
    harbour: "Windward Stair",
    log: "The wind blows dead against us, all the way up the channel.",
    teach: [
      { who: 'hook', text: "Keep the sail struck so the wind can’t touch her, and haul from post to post." },
    ],
    map: [
      '####P##',
      '#dddHd#',
      '#Pdddd#',
      '#ddddP#',
      '#ddddd#',
      '#ddPdd#',
      'Pddddd#',
      '##ddd##',
      '##d.d##',
      '###s###',
      '#######',
    ],
    marks: { buoys: { 1: [1, 6] } },
    facing: 'N', legs: [3, 6],
    crew: { hoist: 1, strike: 1, steady: 2, port: 2, starboard: 2, grapple: 5 },
    needs: ['grapple'],
  },
  {
    name: 'Post to Post', chapter: 3,
    harbour: "Race Rocks",
    log: "The race runs hard onto the rocks.",
    teach: [
      { who: 'hook', text: "Each time we turn, the race carries her a square. Make that square count." },
    ],
    map: [
      '#####P###',
      '#vvvvHvv#',
      '#vvvvvvv#',
      '#Pvvvvvv#',
      '#>vvv^Pv#',
      '#vvvvvvv#',
      '#vvvvvvv#',
      '#s******#',
      '#########',
    ],
    marks: { buoys: { 1: [5, 4] } },
    facing: 'N', legs: [3, 2],
    crew: { hoist: 1, strike: 1, steady: 2, port: 1, starboard: 1, grapple: 3, anchor: 2 },
    needs: ['grapple'],
  },
  {
    name: 'Broken Mast', chapter: 3, brokenMast: true,
    harbour: "Mastless Mooring",
    log: "A gale cracked the mast in the night. No sail today.",
    teach: [
      { who: 'bosun', text: "No sail till the mast’s fixed. Sorry, all!" },
      { who: 'hook', text: "Then it’s the tide, Marlo’s anchor and my hook. A whale in the way blocks the line, mind." },
    ],
    map: [
      '####P##',
      '#v##H##',
      '#vvv..#',
      '#vvv..#',
      '#vvv.P#',
      '#vvv..#',
      '#vvv..#',
      '#***###',
      '#######',
    ],
    marks: { start: [1, 1] },
    facing: 'E', legs: [7],
    crew: { steady: 3, port: 1, starboard: 1, grapple: 2, anchor: 2 },
    beasts: [{ kind: 'whale', at: [3, 2], route: 'SSSS', back: true, phase: 3 }],
    needs: ['grapple', 'anchor'],
  },
  {
    name: 'The Drowned Docks', chapter: 3,
    harbour: 'Drowned Quay',
    log: "The old harbour’s last pilings, a rip current, and a raft of barrels in the way.",
    teach: [
      { who: 'hook', text: "Barrels between us and the post: the hook can’t get past them." },
      { who: 'gunner', text: "I can shoot them, but there’s a rock right behind us. If only something could hold her still against the kick..." },
    ],
    map: [
      '#########',
      '#*svvBP##',
      '##.vv1.##',
      '##*vv*.##',
      '###**#.##',
      '######.##',
      '######H##',
      '#########',
    ],
    facing: 'E', legs: [6, 5],
    crew: { hoist: 1, strike: 1, steady: 4, port: 1, starboard: 2, anchor: 2, fire: 1, grapple: 1 },
    needs: ['anchor', 'fire', 'grapple'],
  },

  /* ---------- Home Waters: everything ---------- */
  {
    name: 'Lighthouse Point', chapter: 4,
    harbour: 'Lighthouse Point',
    log: "Home waters at last: the first light on our own coast.",
    teach: [
      { who: 'captain', text: "Every trick we’ve learned, all in one voyage: the tide, the whale, the barrels and the rip." },
      { who: 'gunner', text: "One ball left, mind. Save it for the barrels!" },
    ],
    map: [
      '##########',
      '#v########',
      '#v####P###',
      '.v...#.H##',
      '#v####>>>*',
      '#v####>>>*',
      '#>1.B.2..#',
      '##########',
    ],
    marks: { start: [1, 1] },
    facing: 'S', legs: [7, 6, 5],
    crew: { hoist: 2, strike: 1, steady: 8, port: 2, starboard: 2, anchor: 2, fire: 1, grapple: 1 },
    beasts: [{ kind: 'whale', at: [0, 3], route: 'EEEE', back: true, phase: 0 }],
    needs: ['anchor', 'fire', 'grapple'],
  },
  {
    name: "Smugglers' Cove", chapter: 4,
    harbour: "Smugglers' Cove",
    log: "The back way into the cove: a rip, a whale road and a cargo someone didn’t want found.",
    teach: [
      { who: 'captain', text: "One Hoist today, so once the sail’s up it stays up. Plan the whole way down before we start!" },
    ],
    map: [
      '########',
      '#s.vv1P#',
      '###**v##',
      '#####v##',
      '##...v.#',
      '#####v##',
      '#HB<<<##',
      '########',
    ],
    marks: { buoys: { 2: [5, 5] } },
    facing: 'E', legs: [3, 5, 7],
    crew: { hoist: 1, steady: 7, port: 1, starboard: 2, anchor: 2, fire: 1, grapple: 1 },
    beasts: [{ kind: 'whale', at: [2, 4], route: 'EEEE', back: true, phase: 4 }],
    needs: ['anchor', 'fire', 'grapple'],
  },
  {
    name: 'The Long Reach', chapter: 4,
    harbour: 'Windward Quay',
    log: "A wind lane runs the length of the reach, straight for home. Then it’s dead against us.",
    teach: [
      { who: 'bosun', text: "One Hoist, and a long lane to run. Once she’s flying, only the anchor will hold her." },
      { who: 'hook', text: "And at the top the wind turns against us. You know what to do." },
    ],
    map: [
      '#######',
      '#.u.2##',
      '##u#u##',
      '##B#u##',
      '##u#H##',
      '##1#P##',
      '##B####',
      '##u####',
      '..u..##',
      '##u####',
      '##.####',
      '##s####',
      '#######',
    ],
    marks: { buoys: { 1: [2, 5] } },
    facing: 'N', legs: [6, 6, 3],
    crew: { hoist: 1, strike: 1, steady: 6, port: 1, starboard: 2, anchor: 2, fire: 2, grapple: 1 },
    beasts: [{ kind: 'whale', at: [0, 8], route: 'EEEE', back: true, phase: 0 }],
    needs: ['anchor', 'fire', 'grapple'],
  },
  {
    name: 'Storm Front', chapter: 4,
    harbour: 'Stormhaven',
    log: "A gale from the north, and the only way on is into its teeth.",
    teach: [
      { who: 'hook', text: "Posts all the way up, like the Windward Stair. But there’s a raft of barrels in one line, and the shore right behind it." },
    ],
    map: [
      '####P##',
      '#dddHd#',
      '#Pdddd#',
      '#ddBdP#',
      '#ddddd#',
      '#ddPdd#',
      'Pddddd#',
      '##ddd##',
      '##d.d##',
      '###s###',
      '#######',
    ],
    marks: { buoys: { 1: [1, 6], 2: [1, 3] } },
    facing: 'N', legs: [3, 3, 7],
    crew: { hoist: 1, strike: 1, steady: 2, port: 2, starboard: 2, anchor: 2, fire: 1, grapple: 5 },
    beasts: [{ kind: 'whale', at: [1, 4], route: 'EEEE', back: true, phase: 3 }],
    needs: ['anchor', 'fire', 'grapple'],
  },
  {
    name: 'Shark Sound', chapter: 4,
    harbour: 'Sharksound',
    log: "Two sharks, two rocks, one narrow way through, and the tide running hard at the far end.",
    teach: [
      { who: 'captain', text: "Read the sharks’ numbers on the water, and thread between them." },
      { who: 'anchor', text: "Where the tide runs into the shore at the bottom there, she can’t stop but at anchor." },
    ],
    map: [
      '#########',
      '#...#...#',
      '#.*.#.*.#',
      '#.......#',
      '#s#####1#',
      '#######v#',
      'PHvv.B.v#',
      '##**#####',
      '#########',
    ],
    marks: { buoys: { 2: [7, 6] } },
    facing: 'N', legs: [8, 2, 8],
    crew: { hoist: 2, strike: 1, steady: 6, port: 2, starboard: 3, anchor: 2, fire: 1, grapple: 1 },
    beasts: [
      { kind: 'shark', at: [1, 1], route: 'EESSWWNN', phase: 0 },
      { kind: 'shark', at: [5, 1], route: 'EESSWWNN', phase: 4 },
    ],
    needs: ['anchor', 'fire', 'grapple'],
  },
  {
    name: 'The Last Maelstrom', chapter: 4,
    harbour: 'Maelstrom Point',
    log: "The tide race runs straight down into the last whirlpool before home.",
    teach: [
      { who: 'captain', text: "The race won’t let her stop, and at the bottom it’s the maelstrom. There’s one post to haul out on: be facing it when she comes by." },
    ],
    map: [
      '#########',
      '###v#####',
      '###v#####',
      '#..v..###',
      '###v#####',
      '###B#####',
      '###vvv.P#',
      '###vvvH##',
      '##...*###',
      '##.@.####',
      '##...####',
      '#########',
    ],
    marks: { start: [3, 1], buoys: { 1: [3, 4] }, flows: { '3,5': 'v' } },
    facing: 'S', legs: [4, 6],
    crew: { hoist: 2, strike: 1, steady: 5, port: 2, starboard: 2, anchor: 2, fire: 1, grapple: 1 },
    beasts: [{ kind: 'whale', at: [1, 3], route: 'EEEE', back: true, phase: 1 }],
    needs: ['anchor', 'fire', 'grapple'],
  },
  {
    name: 'Home', chapter: 4, home: true,
    harbour: 'Home',
    log: "The lighthouse is lit and the whole village is on the quay. One last run, and every trick we know.",
    teach: [
      { who: 'captain', text: "The tide race, the barrels in the lane, the ebb in the harbour mouth, and a shark in the basin. Nearly there, crew." },
    ],
    map: [
      '#########',
      '###.H.###',
      '#.......#',
      '#P##.####',
      '#....####',
      '#v#######',
      '#v#######',
      '#lllBllB#',
      '#######^#',
      '####.##^#',
      '####.##^#',
      '#>>>>>>^#',
      '####.####',
      '#########',
    ],
    marks: { start: [1, 11], buoys: { 1: [7, 9], 2: [1, 7], 3: [4, 4] } },
    facing: 'E', legs: [8, 8, 5, 6],
    crew: { hoist: 1, strike: 1, steady: 10, port: 3, starboard: 3, anchor: 2, fire: 3, grapple: 1 },
    beasts: [
      { kind: 'whale', at: [4, 9], route: 'SSS', back: true, phase: 0 },
      { kind: 'shark', at: [1, 2], route: 'EEEEEE', back: true, phase: 4 },
    ],
    needs: ['anchor', 'fire', 'grapple'],
  },
];
