// Kingdom: the bid for the crown. Five choices after the sixteenth step, different for each state of the realm, each
// stage drawn from a few variants. Your standing is your claim to the throne: it starts from your renown, your name
// and what you carry, rises and falls with each choice, and if it ever falls to nothing the crown is lost. The fifth
// choice decides it.
//
// The old king's court: win the dying ruler's favour against a scheming rival.
// The tyrant's city: take the throne, by rebellion (path 'rebellion') or from inside the court (path 'court').
// The empty throne: win it by arms (path 'arms') or unite the lords behind you (path 'unity').
export default [
  /* ====================== THE OLD KING ====================== */
  { id: 's_old_summons', stage: 1, realm: 'old',
    title: 'The Summons to Court',
    text: 'Heralds ride from {capital}: {ruler} is failing, and has called the worthiest in the realm to court, to choose an heir. Half the kingdom seems to be on the road.',
    left: { label: 'Arrive in splendour', cost: 25, tile: 'city_gate', out: [
      { w: 3, text: 'Silks, a borrowed charger, a boy with a trumpet. Heads turn in the gate, and the old {monarch} hears of it by supper.', claim: 2 },
      { w: 1, text: 'The charger is magnificent and bites a duke. The court talks of nothing else, not kindly.', claim: -1 },
    ], poor: { text: 'Your borrowed finery comes apart at the seams in the palace gate. The court laughs for a week.', claim: -1 } },
    right: { label: 'Walk in with the crowds', tile: 'road', odds: { base: .35, renown: .04 },
      win: { text: 'The crowds that walk with you are chanting your name by the time you reach the gates. Up in the palace, a window opens.', claim: 2, renown: 1 },
      lose: { text: 'Nobody notices one more dusty traveller. You wait four days in the rain for an audience.', claim: -1 } } },
  { id: 's_old_feast', stage: 1, realm: 'old',
    title: 'The Feast of Claimants',
    text: '{Ruler} feasts the claimants in the great hall. Your seat is well below the salt, beside a sour old knight who keeps rubbing his knees.',
    left: { label: 'Rise and toast the king', tile: 'palace', odds: { base: .35, renown: .04, talk: .15 },
      win: { text: 'Your toast is short, and true, and funny. The old {monarch} laughs until they cough, and raises a cup to you.', claim: 2 },
      lose: { text: 'Your toast runs long. Someone yawns. {Rival} smirks into their wine.', claim: -1 } },
    right: { label: 'Befriend the sour knight', tile: 'palace', out: [
      { w: 2, text: 'He is Sir Hollis, the king’s champion once. By the pudding he has sworn to speak for you, and the Knights of the Rose with him.', ally: 'knights', claim: 1 },
      { w: 2, text: 'He wants only to talk about his knees. All night. You learn a great deal about knees.' },
    ] } },

  { id: 's_old_rival', stage: 2, realm: 'old',
    title: 'The Rival Claimant',
    text: '{Rival} has the most men and the fewest scruples. Across the court they smile at you the way a cat smiles at a mousehole.',
    left: { label: 'Challenge them to a duel', tile: 'tourney', fight: { foe: 'champion', name: 'the rival’s champion', power: 10, dmg: 2,
      win: { text: 'Their champion goes down in the sawdust, and the rival goes very pale.', claim: 2 },
      lose: { text: 'You go down in the sawdust. The rival helps you up, in front of everyone, which is worse.', claim: -2 } } },
    right: { label: 'Outmanoeuvre them at court', tile: 'palace', odds: { base: .3, renown: .02, ally: { lords: .2, merchants: .15, church: .1 }, talk: .15 },
      win: { text: 'A word to a lord, a loan to another, a secret to a third. Within the week the rival’s friends are yours.', claim: 2 },
      lose: { text: 'The rival spreads a rumour about you, and it sticks like tar.', claim: -2 } } },
  { id: 's_old_assassin', stage: 2, realm: 'old',
    title: 'A Knife in the Dark',
    text: 'Somebody has paid to make sure you never reach the throne room. A kitchen girl slips you a warning with your bread: tonight.',
    left: { label: 'Lie in wait for the killer', tile: 'palace', fight: { foe: 'assassin', name: 'the assassin', power: 9, dmg: 3,
      win: { text: 'You drag the assassin before the king by the collar. The trail of coin leads straight to {rival}.', claim: 2, renown: 1 },
      lose: { text: 'The assassin is faster than you. You live, but only just, and the court thinks you careless.', claim: -1 } } },
    right: { label: 'Sleep somewhere else', tile: 'garden', odds: { base: .55, ally: { guild: .2, knights: .1 } },
      win: { text: 'You sleep in the hayloft of the royal stables. The assassin finds an empty bed, and a kitchen girl has a new silver ring.', claim: 1 },
      lose: { text: 'The assassin finds the hayloft too. You fight your way out bleeding.', hp: -3 } } },
  { id: 's_old_tourney', stage: 2, realm: 'old',
    title: 'The Tourney of Succession',
    text: 'The old {monarch} would see the heir ride. The lists are painted gold, and every claimant must enter, or send a champion.',
    left: { label: 'Ride in the joust', tile: 'tourney', fight: { foe: 'knight', name: 'the Knight of the Silver Swan', power: 9, dmg: 2,
      win: { text: 'Your lance takes the Silver Swan square on the shield, and the crowd goes wild.', claim: 2, renown: 2 },
      lose: { text: 'You are unhorsed in the first pass, in front of the whole court.', claim: -1 } } },
    right: { label: 'Sponsor a champion', cost: 30, tile: 'tourney', out: [
      { w: 2, text: 'Your champion unhorses three knights in a row. Some of the glory is yours.', claim: 1 },
      { w: 1, text: 'Your champion is thrown in the first pass. Nobody lets you forget whose colours he wore.', claim: -1 },
    ], poor: { text: 'You haven’t the purse to sponsor anyone. The heralds note your absence, loudly.', claim: -1 } } },

  { id: 's_old_riddle', stage: 3, realm: 'old',
    title: 'The Old Ruler’s Question',
    text: '{Ruler} is too weak to rise, but not too weak to test you. "Tell me, claimant. What is the heaviest thing a ruler carries?"',
    left: { label: '"The crown."', tile: 'palace', odds: { base: .3, renown: .02 },
      win: { text: '"Ha. Honest, at least." The old {monarch} closes their eyes, smiling.', claim: 1 },
      lose: { text: '"Wrong. The crown weighs nothing. It is everything under it that weighs." You are sent away.', claim: -1 } },
    right: { label: '"The blame."', tile: 'palace', odds: { base: .45, talk: .1 },
      win: { text: 'A long silence. Then: "Yes. Nobody ever says that." A thin hand squeezes yours.', claim: 2 },
      lose: { text: '"Clever," says the old {monarch}, as if it were an insult.', claim: -1 } } },
  { id: 's_old_physician', stage: 3, realm: 'old',
    title: 'The Physician’s Offer',
    text: 'The royal physician draws you aside. "The king could linger for months. Or not. It would be a mercy, and you would be here when it happens."',
    left: { label: 'Report the physician', tile: 'prison', odds: { base: .5, ally: { church: .15, knights: .1 } },
      win: { text: 'The physician is hanged at dawn. The old {monarch} holds your hand a long while, and calls you honest.', claim: 2 },
      lose: { text: 'The physician has friends. By noon it is you who is accused of plotting.', claim: -2 } },
    right: { label: 'Say nothing, and wait', tile: 'garden', out: [
      { w: 1, text: 'You say nothing. Nothing happens. You begin to wonder whether it was a test, and whether you passed.' },
      { w: 1, text: 'The plot is found out, and so is your silence about it.', claim: -2 },
      { w: 1, text: 'The physician is caught in the act by someone else. In the confusion, your name is spoken kindly.', claim: 1 },
    ] } },
  { id: 's_old_dragon', stage: 3, realm: 'old',
    title: 'The Dragon of the Fells',
    text: '"Bring me the head of the dragon that burns my northern fells," croaks {ruler}, "and the crown is as good as yours."',
    left: { label: 'Hunt the dragon', tile: 'lair', fight: { foe: 'dragon', name: 'the Dragon of the Fells', power: 13, dmg: 3, elite: true,
      win: { text: 'You come back with a head the size of a haywain. The old {monarch} weeps. The court falls silent.', claim: 3, renown: 3 },
      lose: { text: 'You come back scorched, without a head, and the court is kind about it, which is worse.', claim: -1 } } },
    right: { label: 'Bring back a lesser head', tile: 'wizard_tower', odds: { base: .35, ally: { mages: .3, guild: .15 }, talk: .1 },
      win: { text: 'A wizard’s glamour makes a wyvern’s skull look every inch a dragon’s. The old {monarch} is delighted.', claim: 2 },
      lose: { text: 'The court wizard sees through it at a glance. "A wyvern," he announces, to the whole hall.', claim: -2, renown: -2 } } },

  { id: 's_old_cup', stage: 4, realm: 'old',
    title: 'The Poisoned Cup',
    text: 'At the last feast before the naming, the Lord Chancellor fills your cup himself, and smiles a little too widely.',
    left: { label: 'Drink, and smile back', tile: 'palace', out: [
      { w: 2, text: 'Very good wine, and nothing else. The Chancellor looks disappointed. The court saw you drink without blinking.', claim: 1 },
      { w: 1, text: 'It is not only wine. You are sick for three days, and the court decides you are frail.', hp: -2, claim: -1 },
    ] },
    right: { label: 'Swap cups with the Chancellor', tile: 'palace', odds: { base: .4, ally: { guild: .25 } },
      win: { text: 'He drinks, turns grey, and is carried out. By morning his plot has unravelled, and it had your name on it.', claim: 2 },
      lose: { text: 'He sees your hand move. "Treason!" he cries, before anyone has drunk anything at all.', claim: -2 } } },
  { id: 's_old_bishop', stage: 4, realm: 'old',
    title: 'The Bishop’s Roof',
    text: 'The Bishop of {capital} will anoint whoever is named. But bishops have their needs too. "The cathedral roof leaks," she observes.',
    left: { label: 'Pay for a new roof', cost: 40, tile: 'cathedral', out: [
      { w: 3, text: 'Slates of silver. The Bishop’s blessing is warm, public and repeated from the pulpit.', claim: 2, ally: 'church' },
      { w: 1, text: 'The Bishop takes the gold, and blesses you and your rival equally.', claim: 1 },
    ], poor: { text: 'You offer prayers instead of gold. She is not moved, and nor is the roof.', claim: -1 } },
    right: { label: 'Remind her of her vows', tile: 'cathedral', odds: { base: .3, ally: { church: .35 }, renown: .02 },
      win: { text: 'Shamed, she blesses you for nothing, and means it.', claim: 2 },
      lose: { text: 'She remembers that her vows are to the Church, and not to you.', claim: -1 } } },
  { id: 's_old_offer', stage: 4, realm: 'old',
    title: 'The Rival’s Offer',
    text: '{Rival} comes to you at night, alone and unarmed. "Stand aside for me, and you will be my Chancellor. Rich. Safe. Or be my enemy."',
    left: { label: 'Agree, then betray them', tile: 'garden', odds: { base: .4, ally: { guild: .2 }, talk: .1 },
      win: { text: 'You smile and nod, and in the morning you tell the old {monarch} everything. The rival is banished before noon.', claim: 3 },
      lose: { text: 'The rival expected nothing less of you, and moved first.', claim: -3 } },
    right: { label: 'Refuse to their face', tile: 'palace', out: [
      { w: 2, text: 'They bow, coldly, and go. The court hears of it by breakfast, and admires you for it.', claim: 1, renown: 1 },
      { w: 1, text: 'That night their men come for you.', fight: { foe: 'mercenary', name: 'the rival’s men', power: 9, dmg: 2,
        win: { text: 'You hold the stair against them until the guard arrives. The rival is disgraced.', claim: 2 },
        lose: { text: 'They leave you for dead on the stair. You aren’t, quite.', claim: -1 } } },
    ] } },

  { id: 's_old_naming', stage: 5, realm: 'old', final: true,
    title: 'The Naming',
    text: 'In the great bedchamber, {ruler} lies dying. The court holds its breath. A thin hand lifts from the covers, and begins to point…',
    left: { label: 'Kneel, and wait', tile: 'palace', odds: { base: -.1, claim: .085 },
      win: { text: '…at you. "This one," the old {monarch} breathes. One by one, the court kneels to you.', crown: true },
      lose: { text: '…past you, at {rival}. The court kneels. After a moment, so do you. It is over.' } },
    right: { label: 'Seize the crown from its cushion', tile: 'palace', fight: { foe: 'champion', name: 'the Royal Guard', power: 12, dmg: 4,
      win: { text: 'The guard falls back before you. You set the crown on your own head, and dare anyone to take it off.', crown: true, path: 'blade' },
      lose: { text: 'The Royal Guard cuts you down on the steps of the dying king’s bed.', die: 'cut down in the royal bedchamber' } } } },
  { id: 's_old_regents', stage: 5, realm: 'old', final: true,
    title: 'The Council of Regents',
    text: '{Ruler} died in the night without naming anyone. Now the Council of Regents must choose between you and {rival}, and the city waits outside.',
    left: { label: 'Speak before the Council', tile: 'palace', odds: { base: -.1, claim: .08, ally: { lords: .06, merchants: .04 }, talk: .06 },
      win: { text: 'You speak for an hour, and at the end of it the old Regent stands and bows to you. The others follow.', crown: true },
      lose: { text: 'The Council chooses {rival}, eleven votes to four. You are thanked for your interest.' } },
    right: { label: 'Demand trial by combat', tile: 'tourney', fight: { foe: 'champion', name: 'the rival’s champion', power: 12, dmg: 4,
      win: { text: 'Their champion yields in the sawdust, and the old law is the old law. The crown is yours.', crown: true, path: 'blade' },
      lose: { text: 'The old law is the old law, and it is not on your side today.', die: 'killed in a trial by combat' } } } },

  /* ====================== THE TYRANT ====================== */
  { id: 's_ty_how', stage: 1, realm: 'tyrant',
    title: 'The Tyrant’s City',
    text: '{capital} is a city of spikes and informers, and {ruler} sits at the heart of it like a spider. To take the throne, you will have to take it. But how?',
    left: { label: 'Raise the people in revolt', path: 'rebellion', tile: 'bonfire', odds: { base: .4, renown: .03, ally: { rebels: .25 } },
      win: { text: 'In the taverns and the fields, your name becomes a password.', claim: 2 },
      lose: { text: 'The first meeting is betrayed. You escape over the rooftops, alone.', claim: -1 } },
    right: { label: 'Work from inside the court', path: 'court', tile: 'palace', odds: { base: .4, ally: { guild: .2, merchants: .15 }, talk: .1 },
      win: { text: 'A new face at court, with a full purse and a ready smile. Nobody suspects a thing.', claim: 2 },
      lose: { text: 'The spymaster takes an interest in you. You will have to be very careful now.', claim: -1 } } },
  { id: 's_ty_mask', stage: 1, realm: 'tyrant',
    title: 'The Woman in the Mask',
    text: 'A masked woman finds you in an alley. "We want {ruler} gone. The Greenhood can give you an army; the Quiet Hand can give you a key. Choose one."',
    left: { label: 'Take the army', path: 'rebellion', tile: 'war_camp', out: [
      { w: 3, text: 'By the next moon, three hundred outlaws are sharpening billhooks in your name.', claim: 2, ally: 'rebels' },
      { w: 1, text: 'The army is real, but so is the informer among them. You lose a dozen good people in the first week.', claim: 1, hp: -1 },
    ] },
    right: { label: 'Take the key', path: 'court', tile: 'prison', out: [
      { w: 3, text: 'An iron key to a door in the palace that nobody uses, and a thief who knows which stair it opens on.', claim: 2, ally: 'guild' },
      { w: 1, text: 'The key opens nothing but a broom cupboard, and your pocket is lighter for the lesson.', gold: -15 },
    ] } },

  { id: 's_ty_armoury', stage: 2, realm: 'tyrant', path: 'rebellion',
    title: 'Swords for the People',
    text: 'You have the anger of a thousand farmers. What you do not have is swords. The royal armoury has plenty.',
    left: { label: 'Raid the royal armoury', tile: 'castle', fight: { foe: 'soldier', name: 'the armoury guard', power: 9, dmg: 2,
      win: { text: 'Pikes and helms for everyone, and the tyrant’s own seal on the crates.', claim: 2 },
      lose: { text: 'The raid is a rout. The survivors blame you, loudly.', claim: -2 } } },
    right: { label: 'Buy dwarf-steel', cost: 35, tile: 'mine', out: [
      { w: 3, text: 'Good dwarf-steel, and dwarves who know how to use it.', claim: 2 },
      { w: 1, text: 'The dwarves deliver, then sell the tale of it to the tyrant’s spies.', claim: 1 },
    ], poor: { text: 'The dwarves laugh at your purse. Your farmers will fight with flails.', claim: -1 } } },
  { id: 's_ty_gallows', stage: 2, realm: 'tyrant', path: 'rebellion',
    title: 'The Hangman’s Price',
    text: '{Ruler} hangs ten villagers a day until the rebels give you up. The villagers look at you, and say nothing.',
    left: { label: 'Give yourself up', tile: 'gallows', odds: { base: .35, ally: { rebels: .3 }, renown: .03 },
      win: { text: 'The rebels storm the gallows before the trap drops. The story of it runs ahead of you like fire.', claim: 3, renown: 2 },
      lose: { text: 'You are thrown in a cell. The rebels break you out, but it costs them dearly.', claim: -1, hp: -2 } },
    right: { label: 'Strike the gallows at dawn', tile: 'gallows', fight: { foe: 'soldier', name: 'the hangman’s guard', power: 10, dmg: 2,
      win: { text: 'Ropes cut, guards scattered, ten villagers alive. By noon every village for miles is yours.', claim: 2, renown: 1 },
      lose: { text: 'The guard was ready. So was the hangman.', claim: -2 } } } },

  { id: 's_ty_siege', stage: 3, realm: 'tyrant', path: 'rebellion',
    title: 'The Walls of {capital}',
    text: 'Your rebels camp outside the city. The gates are shut, the walls are high, and your army is already hungry.',
    left: { label: 'Storm the walls', tile: 'city_gate', fight: { foe: 'soldier', name: 'the walls of {capital}', power: 11, dmg: 3,
      win: { text: 'Ladders, ropes, fire and luck. By nightfall your banner is on the gatehouse.', claim: 2 },
      lose: { text: 'The walls hold. You leave a great many people at the foot of them.', claim: -2 } } },
    right: { label: 'Starve them out', tile: 'war_camp', odds: { base: .35, ally: { dwarves: .2, merchants: .15, lords: .15 } },
      win: { text: 'Inside the walls the people are hungrier than you. On the ninth night, they open the gates themselves.', claim: 2 },
      lose: { text: 'Your own army starves first. Half of them go home.', claim: -2 } } },
  { id: 's_ty_traitor', stage: 3, realm: 'tyrant', path: 'rebellion',
    title: 'The Traitor in the Camp',
    text: 'One of your captains is selling your plans to the tyrant. You are almost sure which one.',
    left: { label: 'Hang the one you suspect', tile: 'gallows', out: [
      { w: 2, text: 'It was him. The leaks stop.', claim: 1 },
      { w: 1, text: 'It wasn’t him. The leaks go on, and your army grows sullen.', claim: -2 },
    ] },
    right: { label: 'Feed them false plans', tile: 'war_camp', odds: { base: .4, ally: { guild: .25 }, talk: .1 },
      win: { text: 'The tyrant’s army marches smartly off into the wrong valley.', claim: 3 },
      lose: { text: 'The traitor smells the trap and vanishes, with the real plans.', claim: -1 } } },

  { id: 's_ty_champion', stage: 4, realm: 'tyrant', path: 'rebellion',
    title: 'The Tyrant’s Champion',
    text: 'Before the last battle, {ruler} offers single combat: the royal champion against you. Win, and the gates open.',
    left: { label: 'Accept the challenge', tile: 'tourney', fight: { foe: 'champion', name: 'the Tyrant’s Champion', power: 11, dmg: 3, elite: true,
      win: { text: 'The champion falls. The gates open. The tyrant’s soldiers begin, very quietly, to take off their colours.', claim: 3 },
      lose: { text: 'You are carried off the field. The battle goes ahead anyway, without you in it.', claim: -2 } } },
    right: { label: 'Fight it out as an army', tile: 'battlefield', odds: { base: .3, claim: .04, ally: { knights: .15, lords: .15, rebels: .1 } },
      win: { text: 'The tyrant’s line breaks at the second charge.', claim: 2 },
      lose: { text: 'Your line breaks at the first.', claim: -2 } } },
  { id: 's_ty_granary', stage: 4, realm: 'tyrant', path: 'rebellion',
    title: 'The Burning Granaries',
    text: 'Falling back, the tyrant’s soldiers set fire to the city granaries. {capital} will starve this winter.',
    left: { label: 'Put out the fires', tile: 'bonfire', odds: { base: .45, renown: .02 },
      win: { text: 'Soot-black and blistered, you save half the grain. The city will remember who carried the buckets.', claim: 2, renown: 1 },
      lose: { text: 'The fire wins. The city’s hunger turns to anger, and some of it turns on you.', claim: -1, hp: -1 } },
    right: { label: 'Chase down their army', tile: 'battlefield', fight: { foe: 'soldier', name: 'the tyrant’s rearguard', power: 10, dmg: 2,
      win: { text: 'You catch them at the river and they throw down their spears.', claim: 2 },
      lose: { text: 'The rearguard turns on you at the river, and you lose the day.', claim: -1 } } } },

  { id: 's_ty_captain', stage: 2, realm: 'tyrant', path: 'court',
    title: 'The Captain of the Guard',
    text: 'Every lock in the palace answers to Captain Grell. Captain Grell answers to gold, or to fear.',
    left: { label: 'Bribe the captain', cost: 40, tile: 'prison', out: [
      { w: 3, text: 'Grell counts it twice and becomes your very good friend.', claim: 2 },
      { w: 1, text: 'Grell takes the gold, and reports you anyway. At least he looks sorry.', claim: -2 },
    ], poor: { text: 'Your purse is too thin to interest Captain Grell.', claim: -1 } },
    right: { label: 'Blackmail the captain', tile: 'prison', odds: { base: .3, ally: { guild: .3 }, talk: .1 },
      win: { text: 'Grell has a wife in {capital} and another in the country. He becomes your very good friend.', claim: 2 },
      lose: { text: 'Grell has no shame, and a long memory.', claim: -2 } } },
  { id: 's_ty_ledger', stage: 2, realm: 'tyrant', path: 'court',
    title: 'The Spymaster’s Ledger',
    text: 'The spymaster keeps a ledger of every secret in the kingdom, including, as of Tuesday, yours.',
    left: { label: 'Steal the ledger', tile: 'palace', odds: { base: .35, ally: { guild: .3 } },
      win: { text: 'With the ledger in your hands, half the court quietly starts working for you.', claim: 3 },
      lose: { text: 'The spymaster catches you with one hand on the book.', claim: -1, hp: -2 } },
    right: { label: 'Offer them a better master', cost: 25, tile: 'garden', out: [
      { w: 2, text: 'The spymaster sells you everything they know, including the tyrant.', claim: 2 },
      { w: 1, text: 'The spymaster sells you everything they know, and then sells you.', claim: -1 },
    ], poor: { text: 'You offer a better master and an empty purse. The spymaster is not tempted.', claim: -1 } } },

  { id: 's_ty_poison', stage: 3, realm: 'tyrant', path: 'court',
    title: 'Poison or Dagger',
    text: 'The tyrant eats alone, sleeps alone and trusts no one. Still, a way in can always be found.',
    left: { label: 'Poison the wine', tile: 'altar', odds: { base: .3, ally: { guild: .25, mages: .15 } },
      win: { text: '{Ruler} sickens and cannot rise. The court begins to look to whoever seems most ready. That is you.', claim: 3 },
      lose: { text: 'The taster dies instead. The palace is sealed, and the hunt for a poisoner begins.', claim: -2 } },
    right: { label: 'Bribe the taster', cost: 30, tile: 'palace', out: [
      { w: 2, text: 'The taster tastes, and says nothing, and retires to the country a rich man.', claim: 2 },
      { w: 1, text: 'The taster takes your gold and confesses in the same afternoon.', claim: -1 },
    ], poor: { text: 'The taster laughs at your purse, and remembers your face.', claim: -1 } } },
  { id: 's_ty_masque', stage: 3, realm: 'tyrant', path: 'court',
    title: 'The Masquerade',
    text: 'The tyrant holds a masked ball. Everyone will be in disguise, and by midnight the guard will be very drunk.',
    left: { label: 'Strike during the ball', tile: 'palace', fight: { foe: 'soldier', name: 'the tyrant’s guard', power: 8, dmg: 3,
      win: { text: 'Two guards down behind a curtain, and the key to the tyrant’s stair in your glove.', claim: 2 },
      lose: { text: 'The guard is not as drunk as it looked.', claim: -2 } } },
    right: { label: 'Win the court’s hearts', tile: 'garden', odds: { base: .4, renown: .03, talk: .15 },
      win: { text: 'You dance with everyone. By dawn half the court would follow you anywhere, including over a tyrant.', claim: 2 },
      lose: { text: 'You step on a duchess. It is remembered.', claim: -1 } } },

  { id: 's_ty_treasurer', stage: 4, realm: 'tyrant', path: 'court',
    title: 'The Keys of the Treasury',
    text: 'The lords will follow whoever holds the treasury. The treasurer can be persuaded, one way or another.',
    left: { label: 'Buy the treasurer', cost: 50, tile: 'palace', out: [
      { w: 3, text: 'The treasurer hands you the keys with shaking hands.', claim: 3 },
      { w: 1, text: 'The treasurer takes the money and runs, with the keys.', claim: -1 },
    ], poor: { text: 'You haven’t enough to buy a treasurer. You haven’t enough to buy a cup of wine.', claim: -1 } },
    right: { label: 'Threaten the treasurer', tile: 'prison', odds: { base: .35, power: .03, vs: 8, ally: { guild: .15, knights: .1 } },
      win: { text: 'A quiet word and a heavy hand on the shoulder. The keys are yours.', claim: 2 },
      lose: { text: 'The treasurer screams for the guard, and keeps screaming.', claim: -2 } } },
  { id: 's_ty_suspects', stage: 4, realm: 'tyrant', path: 'court',
    title: 'The Tyrant Suspects',
    text: 'Something in {ruler}’s eyes has changed. They know there is a traitor at court, and have begun to test the courtiers one by one.',
    left: { label: 'Face the test', tile: 'palace', odds: { base: .45, talk: .2, ally: { guild: .1 } },
      win: { text: 'You meet the tyrant’s eyes and lie beautifully. You pass.', claim: 1 },
      lose: { text: 'The tyrant’s eyes narrow, and the guards come for you in the night.', claim: -2, hp: -2 } },
    right: { label: 'Leave the city for a while', tile: 'road', out: [
      { w: 1, text: 'Your absence costs you your momentum, and some of your friends.', claim: -1 },
      { w: 1, text: 'While you are away, the tyrant finds a traitor, the wrong one. You come back cleared.', claim: 1 },
    ] } },

  { id: 's_ty_throne', stage: 5, realm: 'tyrant', path: 'rebellion', final: true,
    title: 'The Throne Room',
    text: 'The palace doors come down. {Ruler} waits on the throne with a drawn sword, alone at last.',
    left: { label: 'Duel the tyrant', tile: 'palace', fight: { foe: 'tyrant', name: '{ruler}', power: 13, dmg: 4, elite: true,
      win: { text: 'The tyrant’s sword rings across the marble. The crown rolls to your feet, and the city outside begins to cheer.', crown: true },
      lose: { text: 'The tyrant is better with a sword than anyone had guessed.', die: 'slain by the tyrant on the throne-room steps' } } },
    right: { label: 'Let the people judge them', tile: 'city_gate', odds: { base: -.14, claim: .085, ally: { church: .05, rebels: .05 } },
      win: { text: 'The tyrant is tried in the square and banished in a fishing boat. The crowd will have no one but you.', crown: true },
      lose: { text: 'In the chaos of the trial, a lord with a bigger army claims the crown instead.' } } },
  { id: 's_ty_deed', stage: 5, realm: 'tyrant', path: 'court', final: true,
    title: 'The Last Night of the Tyrant',
    text: 'Everything is in place. The guards are bought, the council is waiting, the door is unlocked. Only the deed remains.',
    left: { label: 'Do it yourself', tile: 'palace', odds: { base: -.12, claim: .075, ally: { guild: .08 }, power: .015, vs: 8 },
      win: { text: 'By morning it is done, and the court kneels to you in the grey light.', crown: true },
      lose: { text: 'The tyrant was waiting for you.', die: 'killed by the tyrant, knife in hand' } },
    right: { label: 'Let the council depose them', tile: 'palace', odds: { base: -.16, claim: .085, ally: { lords: .05, merchants: .05 } },
      win: { text: 'The council votes, and the guard escorts the tyrant to the tower. The crown comes to you on a velvet cushion.', crown: true },
      lose: { text: 'The council loses its nerve at the last moment, and names someone safer.' } } },

  /* ====================== THE EMPTY THRONE ====================== */
  { id: 's_ch_crows', stage: 1, realm: 'chaos',
    title: 'The Empty Throne',
    text: 'No one has sat the throne of {kingdom} in years. Three warlords circle it like crows. You could be a fourth crow, or the one who ends the circling.',
    left: { label: 'Claim it by the sword', path: 'arms', tile: 'war_camp', odds: { base: .35, power: .03, vs: 8, ally: { knights: .15, lords: .1 } },
      win: { text: 'People flock to a winner. Suddenly your banner has an army under it.', claim: 2 },
      lose: { text: 'Your first battle is a rout. You flee with a handful of the loyal.', claim: -1, hp: -1 } },
    right: { label: 'Unite the lords by treaty', path: 'unity', tile: 'manor', odds: { base: .35, renown: .03, ally: { lords: .2, church: .1 }, talk: .1 },
      win: { text: 'A dozen minor lords sign your charter. It is a start.', claim: 2 },
      lose: { text: 'The lords laugh at your charter, and use it to light their pipes.', claim: -1 } } },
  { id: 's_ch_moot', stage: 1, realm: 'chaos',
    title: 'The Moot at Crowstone',
    text: 'The lords of {kingdom} gather at the Crowstone to choose a king, the old way. They will hear anyone who can stand on the stone and not be pulled down.',
    left: { label: 'Speak at the Moot', path: 'unity', tile: 'stones', odds: { base: .35, renown: .04, talk: .15 },
      win: { text: 'You speak of bread and roads and peace, and the lords go quiet.', claim: 2 },
      lose: { text: 'You are pulled off the stone by the ankles.', claim: -1 } },
    right: { label: 'Make it a war council', path: 'arms', tile: 'war_camp', odds: { base: .35, power: .03, vs: 8, ally: { knights: .1, dwarves: .1 } },
      win: { text: 'By sunset the Moot has become an army, and you are at its head.', claim: 2 },
      lose: { text: 'The Moot breaks up in a brawl, and you get the worst of it.', claim: -1, hp: -1 } } },

  { id: 's_ch_host', stage: 2, realm: 'chaos', path: 'arms',
    title: 'The Warlord’s Host',
    text: '{Warlord} marches on you with a thousand men, and carts of hanged men behind them as a warning.',
    left: { label: 'Meet them in the field', tile: 'battlefield', fight: { foe: 'knight', name: '{warlord}’s host', power: 11, dmg: 3,
      win: { text: 'The host breaks and runs. {Warlord}’s banner is in the mud, and your army is twice the size it was.', claim: 3 },
      lose: { text: 'You leave the field in a cart of your own.', claim: -2 } } },
    right: { label: 'Ambush them in the hills', tile: 'pass', odds: { base: .35, ally: { rebels: .2, dwarves: .15 } },
      win: { text: 'Rocks, arrows and a narrow pass. The host never reaches you.', claim: 2 },
      lose: { text: 'They send scouts first. You are the ones ambushed.', claim: -2, hp: -1 } } },
  { id: 's_ch_sellswords', stage: 2, realm: 'chaos', path: 'arms',
    title: 'The Black Lantern Company',
    text: 'The Black Lantern Company sells its swords to anyone. Right now they are selling them to {warlord}.',
    left: { label: 'Outbid the warlord', cost: 45, tile: 'war_camp', out: [
      { w: 3, text: 'The Black Lantern turns its coat, and its lanterns, your way.', claim: 2 },
      { w: 1, text: 'They take your gold, and desert in the night anyway.', claim: -1 },
    ], poor: { text: 'The captain looks in your purse and laughs until he coughs.', claim: -1 } },
    right: { label: 'Fight the sellswords', tile: 'battlefield', fight: { foe: 'mercenary', name: 'the Black Lantern Company', power: 10, dmg: 2,
      win: { text: 'Sellswords don’t die for anyone. They surrender, and ask whether you are hiring.', claim: 2 },
      lose: { text: 'The Black Lantern earns its pay.', claim: -2 } } } },

  { id: 's_ch_river', stage: 3, realm: 'chaos', path: 'arms',
    title: 'The Burned Bridges',
    text: '{Warlord2} has burned every bridge on the river, and your army is waiting on the wrong bank.',
    left: { label: 'Ford the river at night', tile: 'ferry', odds: { base: .45, renown: .01 },
      win: { text: 'Cold, silent and soaked to the neck, you are across by dawn and in their camp by breakfast.', claim: 2 },
      lose: { text: 'The river takes a hundred of your people, and their courage with them.', claim: -2 } },
    right: { label: 'Build a bridge', cost: 30, tile: 'bridge', out: [
      { w: 3, text: 'Dwarf engineers throw a bridge across in two days. The warlord never sees you coming.', claim: 2 },
      { w: 1, text: 'The bridge takes a fortnight. The warlord uses it too.' },
    ], poor: { text: 'No gold, no bridge. The army sits on the bank and eats your stores.', claim: -1 } } },
  { id: 's_ch_keep', stage: 3, realm: 'chaos', path: 'arms',
    title: 'Siege of the Warlord’s Keep',
    text: '{Warlord2} has shut themselves up in a keep on a crag, with a year of bread and a well that never runs dry.',
    left: { label: 'Storm the keep', tile: 'castle', fight: { foe: 'soldier', name: 'the keep’s defenders', power: 11, dmg: 3,
      win: { text: 'Over the walls at dawn. {Warlord2} surrenders in a nightshirt.', claim: 3 },
      lose: { text: 'The crag is steeper than it looked from below.', claim: -2 } } },
    right: { label: 'Tunnel under the walls', tile: 'mine', odds: { base: .3, ally: { dwarves: .35, rebels: .1 } },
      win: { text: 'The wall comes down with a noise heard in three shires.', claim: 2 },
      lose: { text: 'The tunnel floods. The warlord sends down a jug of wine, as a joke.', claim: -2 } } },

  { id: 's_ch_last', stage: 4, realm: 'chaos', path: 'arms',
    title: 'The Last Warlord',
    text: 'Only {warlord} still stands against you. They offer single combat to spare their soldiers. Or you could spare them.',
    left: { label: 'Fight the warlord yourself', tile: 'battlefield', fight: { foe: 'knight', name: '{warlord}', power: 12, dmg: 3, elite: true,
      win: { text: 'The warlord yields, and their army kneels in the rain.', claim: 3 },
      lose: { text: 'You are beaten in front of both armies.', claim: -2 } } },
    right: { label: 'Offer the warlord a lordship', tile: 'manor', odds: { base: .4, talk: .15, renown: .02 },
      win: { text: 'They kneel, and their army with them. It is cheaper than a battle, and just as final.', claim: 2 },
      lose: { text: 'They take the lordship, and slide a knife into your side at the feast.', claim: -2, hp: -1 } } },
  { id: 's_ch_fever', stage: 4, realm: 'chaos', path: 'arms',
    title: 'Fever in the Camp',
    text: 'Camp fever runs through your army. Half your soldiers cannot stand, and the enemy is two days away.',
    left: { label: 'Tend the sick yourself', tile: 'camp', out: [
      { w: 2, text: 'You carry water and hold hands through the worst nights. They will follow you anywhere now.', claim: 2, renown: 2 },
      { w: 1, text: 'You catch it, and nearly die of it. They follow you anyway.', claim: 1, hp: -2 },
    ] },
    right: { label: 'Leave the sick and march', tile: 'road', odds: { base: .45, power: .02 },
      win: { text: 'A hard march, a quick victory. Nobody asks about the sick.', claim: 1 },
      lose: { text: 'An army that abandons its own soon abandons its captain.', claim: -2 } } },

  { id: 's_ch_bishop', stage: 2, realm: 'chaos', path: 'unity',
    title: 'The Frightened Bishop',
    text: 'The Dawn Church could make your claim holy, if you can steady a very frightened old bishop long enough to bless it.',
    left: { label: 'Ask for a blessing', tile: 'cathedral', odds: { base: .3, ally: { church: .35 }, renown: .03 },
      win: { text: 'The old bishop’s hands shake, but the blessing doesn’t.', claim: 2 },
      lose: { text: 'The bishop blesses you, then a warlord, then another warlord, to be safe.', claim: -1 } },
    right: { label: 'Pay for the blessing', cost: 35, tile: 'cathedral', out: [
      { w: 3, text: 'Gold soothes the bishop wonderfully. The blessing is long and very loud.', claim: 2 },
      { w: 1, text: 'The blessing is a little… generic.', claim: 1 },
    ], poor: { text: 'The bishop looks at your purse, and remembers an urgent appointment.', claim: -1 } } },
  { id: 's_ch_grievances', stage: 2, realm: 'chaos', path: 'unity',
    title: 'The Lords’ Grievances',
    text: 'Every lord wants something: land, a marriage, a feud avenged. You cannot give everyone everything.',
    left: { label: 'Give the lords land', tile: 'manor', out: [
      { w: 2, text: 'Charters, seals, borders drawn on maps. The Marcher Lords are pleased.', claim: 2, ally: 'lords' },
      { w: 1, text: 'The land you promised had already been promised. Twice.', claim: -1 },
    ] },
    right: { label: 'Give them justice instead', tile: 'palace', odds: { base: .4, renown: .03, talk: .1 },
      win: { text: 'You judge each quarrel fairly, and in public. Even the losers respect it.', claim: 2, renown: 1 },
      lose: { text: 'Everyone leaves your court equally angry.', claim: -1 } } },

  { id: 's_ch_wedding', stage: 3, realm: 'chaos', path: 'unity',
    title: 'The Wedding Alliance',
    text: '{Warlord2} offers their heir’s hand in marriage: an alliance, an army, and perhaps a spouse with a knife under the pillow.',
    left: { label: 'Accept the match', tile: 'garden', out: [
      { w: 2, text: 'A grand wedding. Two banners are sewn into one.', claim: 3 },
      { w: 1, text: 'A wedding, a feast and, on the wedding night, the knife.', claim: 1, hp: -2 },
    ] },
    right: { label: 'Decline, politely', tile: 'palace', odds: { base: .45, talk: .15 },
      win: { text: 'You decline so gracefully that {warlord2} thinks it was their idea.', claim: 1 },
      lose: { text: 'An insult {warlord2} will not forget, and does not.', claim: -2 } } },
  { id: 's_ch_famine', stage: 3, realm: 'chaos', path: 'unity',
    title: 'The Famine Winter',
    text: 'Winter comes early. The people of {capital} are starving, and the lords are hoarding their grain.',
    left: { label: 'Buy grain for the city', cost: 30, tile: 'market', out: [
      { text: 'Carts of grain roll through the city gate with your banner on them. {capital} will not forget it.', claim: 3, renown: 2 },
    ], poor: { text: 'You have nothing to give but promises, and the city has had plenty of those.', claim: -1 } },
    right: { label: 'Force the lords to share', tile: 'manor', odds: { base: .35, power: .02, vs: 8, ally: { lords: .15, knights: .15 } },
      win: { text: 'You open the lords’ granaries at spearpoint. The people cheer; the lords remember.', claim: 2 },
      lose: { text: 'The lords close ranks against you.', claim: -2 } } },

  { id: 's_ch_crown', stage: 4, realm: 'chaos', path: 'unity',
    title: 'The Crown in the Dust',
    text: 'In the looted treasury you find it: the old crown of {kingdom}, dented and dusty. They say it burns the brow of a false king.',
    left: { label: 'Try it on', tile: 'ruins', odds: { base: .25, claim: .07, trait: { royal_blood: .3 } },
      win: { text: 'It fits. It does not burn. The lords who saw it go very quiet.', claim: 3 },
      lose: { text: 'It burns. You tear it off with blistered hands.', hp: -2, claim: -1 } },
    right: { label: 'Keep it for the coronation', tile: 'palace', out: [
      { w: 2, text: 'You lock it away. Word gets out that the crown is in your keeping, and that is almost as good.', claim: 1 },
      { w: 1, text: 'You lock it away. In the morning the chest is empty.', claim: -1 },
    ] } },
  { id: 's_ch_knife', stage: 4, realm: 'chaos', path: 'unity',
    title: 'A Knife at the Peace Talks',
    text: 'An assassin strikes at the peace talks. Somebody does not want this realm united.',
    left: { label: 'Shield the old bishop', tile: 'cathedral', fight: { foe: 'assassin', name: 'the assassin', power: 9, dmg: 3,
      win: { text: 'You take the knife meant for the bishop on your bracer, and put the assassin on the floor.', claim: 2, renown: 2 },
      lose: { text: 'You are too slow. The bishop lives; your reputation does not.', claim: -1 } } },
    right: { label: 'Blame the warlord for it', tile: 'palace', odds: { base: .4, talk: .15, ally: { guild: .1 } },
      win: { text: 'Every eye turns to {warlord}. The lords close ranks, around you.', claim: 2 },
      lose: { text: 'The lie is found out by supper.', claim: -2 } } },

  { id: 's_ch_field', stage: 5, realm: 'chaos', path: 'arms', final: true,
    title: 'The Field of Crowns',
    text: 'The last battle. The lords who are left watch from the hills to see who wins, and whoever does will be crowned on this field.',
    left: { label: 'Lead the charge', tile: 'battlefield', fight: { foe: 'knight', name: 'the last army of {kingdom}', power: 12, dmg: 4,
      win: { text: 'The enemy breaks. On the hills, the lords take off their helmets. Someone finds a crown in a baggage cart.', crown: true },
      lose: { text: 'You go down at the front of the charge.', die: 'killed at the head of the charge on the Field of Crowns' } } },
    right: { label: 'Hold the line; wait', tile: 'war_camp', odds: { base: -.08, claim: .085 },
      win: { text: 'They charge. They break on your line like surf. By sunset the lords are kneeling in the mud.', crown: true },
      lose: { text: 'You wait. They wait. In the end a third army arrives, and it is not yours.' } } },
  { id: 's_ch_acclaim', stage: 5, realm: 'chaos', path: 'unity', final: true,
    title: 'The Coronation Moot',
    text: 'The lords of {kingdom} gather to acclaim a ruler. Every eye is on you, and every hand is on a sword. In the middle of the hall, an old sword stands in a stone.',
    left: { label: 'Swear to rule for all', tile: 'palace', odds: { base: -.1, claim: .085, renown: .01 },
      win: { text: 'You swear. They roar. One by one, the lords kneel, and the realm has a ruler again.', crown: true },
      lose: { text: 'You swear. Silence. Then, one by one, the lords turn their backs.' } },
    right: { label: 'Draw the sword from the stone', tile: 'stones', odds: { base: -.1, claim: .05, relic: { kingsblade: .5, old_banner: .2 }, trait: { royal_blood: .25 } },
      win: { text: 'The sword slides free as though it had been waiting for you. Nobody breathes. Then everyone kneels.', crown: true },
      lose: { text: 'The sword doesn’t move. Somebody laughs. Then everyone does.' } } },
];
